### ISSUE TITLE
Indent menu when first menu item is not rendered all the way on the left side.

### ISSUE THREAD

**Issue by joshka** [shuoli84/tui-menu#4]
I wanted to put an app title at the start of the line, but noticed that the menu renders at the left side of the window:

```rust
impl Widget for &mut App {
    fn render(self, area: Rect, buf: &mut Buffer) {
        use Constraint::*;
        let [top, main] = Layout::vertical([Length(1), Fill(1)]).areas(area);
        let [title, menu] = Layout::horizontal([Length(10), Fill(1)]).areas(top);

        Paragraph::new(self.content.as_str())
            .block(Block::bordered().title("Content").on_black())
            .render(main, buf);

        "tui-menu"
            .bold()
            .blue()
            .to_centered_line()
            .render(title, buf);

        // draw menu last, so it renders on top of other content
        Menu::new().render(menu, buf, &mut self.menu);
    }
}
```
Renders as:

![demo](https://github.com/shuoli84/tui-menu/assets/381361/f0e51a79-3319-4676-a89a-2676a6e022f1)

This is probably a super easy fix, but I wanted to check if @shuoli84 had any feedback before implementing it.
It would be a good idea to indent

**Comment by shuoli84** [comment]
That's a nice feature to implement. 👍 
The drop-down items should align with it's menu item. Also at the right edge of screen, it's better to adjust the drop-down menu's x to avoid clipping.
